### ISSUE TITLE
Costum slide css class

### ISSUE THREAD

**Issue by davide97g** [davide97g/ml-js-impress#2]
Create a costum css class that will replace the default slide of impress.js.
The slide class should have the following properties:
- [x]  width and height quickly resizable with extra classes addictions
- [x]  be able to set background and text color in order to improve readability
- [x] pure css only

**Comment by davide97g** [comment]
Class **card** has been created.
``` css
.card {
  background: #fff;
  border-radius: 2px;
  color: black;
  margin: 1rem;
  padding-bottom: 1rem;
  padding-top: 1rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2), 0 1px 2px rgba(0, 0, 0, 0.35);
  transition: all 0.8s cubic-bezier(0.25, 0.8, 0.25, 1);
}
.card:hover {
  box-shadow: 0 14px 28px rgba(0, 0, 0, 0.25), 0 10px 10px rgba(0, 0, 0, 0.22);
}
.blue {
  background: rgb(103, 166, 202);
  color: #fff;
}
.green {
  background: rgb(103, 202, 116);
  color: #fff;
}
.big {
  width: 1300px;
  height: 900px;
}
.medium {
  width: 900px;
  height: 700px;
}
.small {
  width: 700px;
  height: 500px;
}
```
